### ISSUE TITLE
Add "dyna" license increment in the license mechanism

### ISSUE THREAD

**Issue by rajesh1359** [ansys/pydpf-core#875]
### Description of the feature

For pyDPF for ls-dyna, user having just dyna solver license may not have the compatible license increments. We need to enable increment 'dyna' as well.

**Comment by PProfizi** [comment]
@rlagha, @anslpa

**Comment by PProfizi** [comment]
Hi @rajesh1359! Thank you for pointing this out! 
We also noticed that the license increment `advanced_meshing` should be available with the LS-Dyna solver, and this one is accepted by DPF.
Users having LS-Dyna should have access to this increment (if I understood correctly) and DPF should then work using it. Did you raise the issue based on an actual impossibility to use DPF, or is it due to reading the list of accepted license increments in the documentation?

**Comment by PProfizi** [comment]
Closing this issue as fixed after checking on my end
